site_name: SafeCloset
site_description: 'SafeCloset, a secure cross-platform secret holder'
site_url: https://dystroy.org/safecloset
repo_url: https://github.com/Canop/safecloset
edit_uri: ''

nav:
        - Overview: index.md
        - Features: features.md
        - Install: install.md
        - Usage: usage.md
        - Community: community.md

extra_css:
        - css/extra.css
        - css/link-to-dystroy.css

extra_javascript:
        - js/autoclose-tree.js
        - js/link-to-dystroy.js

theme:
        name: mkdocs
        nav_style: dark
        custom_dir: custom_theme
        highlightjs: true
        hljs_style: Dracula
        hljs_languages:
                - yaml
                - ini
                - css
                - rust

markdown_extensions:
        - admonition
        - def_list
